package com.vulncheck;

public enum MutationType {
    UPDATE_PROPERTY,
    UPDATE_DIRECT_DEPENDENCY,
    UPDATE_DEPENDENCY_MANAGEMENT,
    UPDATE_IMPORTED_BOM,
    UPDATE_PARENT_DEPENDENCY,
    UPDATE_PARENT_POM
}
